# Generated by Django 4.1.3 on 2022-11-07 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudVianda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.CharField(choices=[('SEMANAL', 'SEMANAL'), ('QUINCELA', 'QUINCENAL')], default='SEMANAL', max_length=10)),
                ('tipoMenu', models.CharField(choices=[('VEGETARIANO', 'VEGETARIANO'), ('DIABETICO', 'DIABETICO'), ('NORMAL', 'NORMAL')], default='NORMAL', max_length=15)),
                ('fechaInicioPedidoVianda', models.DateField()),
                ('cantidadViandas', models.IntegerField()),
                ('tipoPlato', models.ManyToManyField(to='vianda.tipoplato')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
