# Generated by Django 4.1.3 on 2022-11-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vianda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudvianda',
            name='estado',
            field=models.CharField(choices=[('CANCELADO', 'CANCELADO'), ('CONFIRMADO', 'CONFIRMADO'), ('PENDIENTE', 'PENDIENTE')], default='PENDIENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='solicitudvianda',
            name='frecuencia',
            field=models.CharField(choices=[('QUINCELA', 'QUINCENAL'), ('SEMANAL', 'SEMANAL')], default='SEMANAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='solicitudvianda',
            name='tipoMenu',
            field=models.CharField(choices=[('DIABETICO', 'DIABETICO'), ('NORMAL', 'NORMAL'), ('VEGETARIANO', 'VEGETARIANO')], default='NORMAL', max_length=15),
        ),
    ]
